### ISSUE TITLE
how many epoch is enough for single category？

### ISSUE THREAD

**Issue by bigKoki** [kimren227/ExtrudeNet#1]
I'm traing your code on category plane,it shows that training needs 10000 epoches,and the model will save if current test loss is lower than before,i want wo know how many epoch is enough for single category in your ex.Thank you very much!!!

**Comment by kimren227** [comment]
I simply leave the training code running, and occasionally check the results by running the "eval.py". If you feel the results are satisfactory, you can stop the training at any time.

**Comment by bigKoki** [comment]
> I simply leave the training code running, and occasionally check the results by running the "eval.py". If you feel the results are satisfactory, you can stop the training at any time.

thank you very much!
i have trained category bench for about 4000 epoches,and my val set and test set is same.In traing,the val f1 score is about 0.8,but when i run eval.py,the f1 score became about 0.4,i want to know is it normal？
secondly, i see that you claim the result can be imported to cad software for further editing, but there is no export script in your code, did you get the result and input them into cad software by hand? and many cad software only support B-spline curve or bezier curve but not national bezier curve, how did you solve this problem?
i'm sorry for so many questions, i wish you can talk about these if you have time, thanks!!!

**Comment by bigKoki** [comment]
> > I simply leave the training code running, and occasionally check the results by running the "eval.py". If you feel the results are satisfactory, you can stop the training at any time.
> 
> thank you very much! i have trained category bench for about 4000 epoches,and my val set and test set is same.In traing,the val f1 score is about 0.8,but when i run eval.py,the f1 score became about 0.4,i want to know is it normal？ secondly, i see that you claim the result can be imported to cad software for further editing, but there is no export script in your code, did you get the result and input them into cad software by hand? and many cad software only support B-spline curve or bezier curve but not national bezier curve, how did you solve this problem? i'm sorry for so many questions, i wish you can talk about these if you have time, thanks!!!

i just see that in eval.py,this word"testing_points = testing_points.to(device)*3",  the "*3" should be removed, it will lead to wrong answer.

**Comment by kimren227** [comment]
> 

1) This is strange, it should be the same. Can you take a look at the generated mesh? If the mesh looks ok, there might be a bug when printing the numbers.

2) I Implemented a plugin for Autodesk Fusion360. Its python API supports NURBS, you can take a look at [here](https://help.autodesk.com/view/fusion360/ENU/?guid=GUID-348710dc-13fe-43a3-af51-63c2f594ce58) on creating a 2D NURBS Sketch, and [here](https://help.autodesk.com/view/fusion360/ENU/?guid=GUID-CB1A2357-C8CD-474D-921E-992CA3621D04) for creating extrusion from the 2D sketch.

**Comment by bigKoki** [comment]
> 

thanks for your reply, the bug is in eval.py,this line "testing_points = testing_points.to(device)*3", the "*3" should be removed, it will lead to wrong answer.

**Comment by kimren227** [comment]
> 

That's a good catch! (I don't know why I added a *3 there.....). If removing that solves your problem, feel free to open a PR. Thanks.

**Comment by bigKoki** [comment]
> > 
> 
> That's a good catch! (I don't know why I added a *3 there.....). If removing that solves your problem, feel free to open a PR. Thanks.

hello,i just follow your guidance to try to create a fusion 360 script,but i found there is no function to add a nurbscurve2d object into sketch(only nurbscurve3d supported by sketchFixedSplines.addByNurbsCurve).could you please talk about how you solve this?  Thanks!

**Comment by kimren227** [comment]
I lost my plugin during a system reinstall... But I managed to find an old script of mine, you can give this a shot. 

```#Author-
#Description-

import adsk.core, adsk.fusion, adsk.cam, traceback
from random import random
def run(context):
    ui = None
    try:
        app = adsk.core.Application.get()
        ui  = app.userInterface
        ui.messageBox('Hello script')
        global fusion
        fusion = adsk.core.Application.get( )
        design = adsk.fusion.Design.cast( fusion.activeProduct )
        #-- Fusion uses centimeters as native units XD
        #--
        mm = 0.1
        #-- Create New Component
        #--
        rootComp = design.rootComponent
        extrudes = rootComp.features.extrudeFeatures
        sketches = rootComp.sketches

        primitives = []

        all_points = [[[ 4.00304950e+00, -2.00906398e-01],
                    [ 7.60428619e+00,  0.00000000e+00],
                    [ 8.52413470e+00,  8.52413470e+00],
                    [ 4.26206735e+00,  7.09705284e+00]],

                    [[ 4.26206735e+00,  7.09705284e+00],
                    [ 3.47185591e-16,  5.66997099e+00],
                    [-1.34324906e+00,  1.34324906e+00],
                    [-7.67891902e-01,  6.71624530e-01]],

                    [[-7.67891902e-01,  6.71624530e-01],
                    [-1.92534745e-01,  2.35787059e-17],
                    [-6.03478201e+00, -6.03478201e+00],
                    [-3.01739100e+00, -9.76179293e+00]],

                    [[-3.01739100e+00, -9.76179293e+00],
                    [-2.47785307e-15, -1.34888039e+01],
                    [ 4.01812797e-01, -4.01812797e-01],
                    [ 4.00304950e+00, -2.00906398e-01]]]
        primitives.append([all_points, 44.34972*2])

        all_points = [[[ 6.83230123e-01, -1.36102995e-01],
                    [ 1.09425426e+00,  0.00000000e+00],
                    [ 5.25406390e+00,  5.25406390e+00],
                    [ 2.62703195e+00,  6.01300564e+00]],

                    [[ 2.62703195e+00,  6.01300564e+00],
                    [ 4.14662184e-16,  6.77194738e+00],
                    [-2.29902060e-01,  2.29902060e-01],
                    [-7.42584504e+00,  1.14951030e-01]],

                    [[-7.42584504e+00,  1.14951030e-01],
                    [-1.46217880e+01,  1.79065259e-15],
                    [-3.84140775e+00, -3.84140775e+00],
                    [-1.92070387e+00, -3.38228415e+00]],

                    [[-1.92070387e+00, -3.38228415e+00],
                    [-5.36975882e-16, -2.92316055e+00],
                    [ 2.72205990e-01, -2.72205990e-01],
                    [ 6.83230123e-01, -1.36102995e-01]]]
        primitives.append([all_points, 44.34972*2])

        all_points = [[[ 1.32009169e+01, -1.32793298e+00],
                    [ 2.37459679e+01,  0.00000000e+00],
                    [ 3.25622607e+00,  3.25622607e+00],
                    [ 1.62811303e+00,  2.81056297e+00]],

                    [[ 1.62811303e+00,  2.81056297e+00],
                    [ 1.44808353e-16,  2.36489987e+00],
                    [-3.47359254e+00,  3.47359254e+00],
                    [-5.70579875e+00,  1.73679627e+00]],

                    [[-5.70579875e+00,  1.73679627e+00],
                    [-7.93800497e+00,  9.72125238e-16],
                    [-5.49562199e+00, -5.49562199e+00],
                    [-2.74781099e+00, -3.17571897e+00]],

                    [[-2.74781099e+00, -3.17571897e+00],
                    [-1.57210839e-16, -8.55815947e-01],
                    [ 2.65586596e+00, -2.65586596e+00],
                    [ 1.32009169e+01, -1.32793298e+00]]]
        primitives.append([all_points, 43.41156*2])

        all_points = [[[ 1.52724363e+01, -1.06590506e+01],
                    [ 9.22677135e+00,  0.00000000e+00],
                    [ 2.00586698e+01,  2.00586698e+01],
                    [ 1.00293349e+01,  1.72432240e+01]],

                    [[ 1.00293349e+01,  1.72432240e+01],
                    [ 8.83446622e-16,  1.44277782e+01],
                    [-1.52736686e+01,  1.52736686e+01],
                    [-1.46296922e+01,  7.63683429e+00]],

                    [[-1.46296922e+01,  7.63683429e+00],
                    [-1.39857159e+01,  1.71275622e-15],
                    [-1.99091489e+01, -1.99091489e+01],
                    [-9.95457446e+00, -1.62999738e+01]],

                    [[-9.95457446e+00, -1.62999738e+01],
                    [-2.33126191e-15, -1.26907988e+01],
                    [ 2.13181012e+01, -2.13181012e+01],
                    [ 1.52724363e+01, -1.06590506e+01]]]
        primitives.append([all_points, 1.9763523*2])

        all_points = [[[ 1.52724363e+01, -1.06590506e+01],
                    [ 9.22677135e+00,  0.00000000e+00],
                    [ 2.00586698e+01,  2.00586698e+01],
                    [ 1.00293349e+01,  1.72432240e+01]],

                    [[ 1.00293349e+01,  1.72432240e+01],
                    [ 8.83446622e-16,  1.44277782e+01],
                    [-1.52736686e+01,  1.52736686e+01],
                    [-1.46296922e+01,  7.63683429e+00]],

                    [[-1.46296922e+01,  7.63683429e+00],
                    [-1.39857159e+01,  1.71275622e-15],
                    [-1.99091489e+01, -1.99091489e+01],
                    [-9.95457446e+00, -1.62999738e+01]],

                    [[-9.95457446e+00, -1.62999738e+01],
                    [-2.33126191e-15, -1.26907988e+01],
                    [ 2.13181012e+01, -2.13181012e+01],
                    [ 1.52724363e+01, -1.06590506e+01]]]
        primitives.append([all_points, 1.9763523*2])


        for primitive in primitives:
            all_points, extrude_height = primitive
            sketch = sketches.add(rootComp.xZConstructionPlane)
            degree = 3
            knots = [0, 0, 0, 0, 1, 1, 1, 1]
            weights = [1, 1, 1, 1]
            # nc = nurbs.controlPointCount
            splines = sketch.sketchCurves.sketchFixedSplines
            splines.isFixed=False



            for control_points in all_points:
                point1 = adsk.core.Point3D.create (control_points[0][0],control_points[0][1],0)
                point2 = adsk.core.Point3D.create (control_points[1][0],control_points[1][1],0)
                point3 = adsk.core.Point3D.create (control_points[2][0],control_points[2][1],0)
                point4 = adsk.core.Point3D.create (control_points[3][0],control_points[3][1],0)
                points = [point1, point2, point3, point4]
                nurbs = adsk.core.NurbsCurve3D.createRational (points, degree, knots, weights, False)
                fixed_splines = splines.addByNurbsCurve(nurbs)
                fixed_splines.isReference =False
            distance = adsk.core.ValueInput.createByReal(extrude_height)
            extrude1 = extrudes.addSimple(sketch.profiles.item(0), distance, adsk.fusion.FeatureOperations.NewBodyFeatureOperation)
    except:
        if ui:
            ui.messageBox('Failed:\n{}'.format(traceback.format_exc()))
```

**Comment by bigKoki** [comment]
> 

thansk a lot,it helps greatly！

**Comment by bigKoki** [comment]
> I lost my plugin during a system reinstall... But I managed to find an old script of mine, you can give this a shot.
> 
> ```
> #Description-
> 
> import adsk.core, adsk.fusion, adsk.cam, traceback
> from random import random
> def run(context):
>     ui = None
>     try:
>         app = adsk.core.Application.get()
>         ui  = app.userInterface
>         ui.messageBox('Hello script')
>         global fusion
>         fusion = adsk.core.Application.get( )
>         design = adsk.fusion.Design.cast( fusion.activeProduct )
>         #-- Fusion uses centimeters as native units XD
>         #--
>         mm = 0.1
>         #-- Create New Component
>         #--
>         rootComp = design.rootComponent
>         extrudes = rootComp.features.extrudeFeatures
>         sketches = rootComp.sketches
> 
>         primitives = []
> 
>         all_points = [[[ 4.00304950e+00, -2.00906398e-01],
>                     [ 7.60428619e+00,  0.00000000e+00],
>                     [ 8.52413470e+00,  8.52413470e+00],
>                     [ 4.26206735e+00,  7.09705284e+00]],
> 
>                     [[ 4.26206735e+00,  7.09705284e+00],
>                     [ 3.47185591e-16,  5.66997099e+00],
>                     [-1.34324906e+00,  1.34324906e+00],
>                     [-7.67891902e-01,  6.71624530e-01]],
> 
>                     [[-7.67891902e-01,  6.71624530e-01],
>                     [-1.92534745e-01,  2.35787059e-17],
>                     [-6.03478201e+00, -6.03478201e+00],
>                     [-3.01739100e+00, -9.76179293e+00]],
> 
>                     [[-3.01739100e+00, -9.76179293e+00],
>                     [-2.47785307e-15, -1.34888039e+01],
>                     [ 4.01812797e-01, -4.01812797e-01],
>                     [ 4.00304950e+00, -2.00906398e-01]]]
>         primitives.append([all_points, 44.34972*2])
> 
>         all_points = [[[ 6.83230123e-01, -1.36102995e-01],
>                     [ 1.09425426e+00,  0.00000000e+00],
>                     [ 5.25406390e+00,  5.25406390e+00],
>                     [ 2.62703195e+00,  6.01300564e+00]],
> 
>                     [[ 2.62703195e+00,  6.01300564e+00],
>                     [ 4.14662184e-16,  6.77194738e+00],
>                     [-2.29902060e-01,  2.29902060e-01],
>                     [-7.42584504e+00,  1.14951030e-01]],
> 
>                     [[-7.42584504e+00,  1.14951030e-01],
>                     [-1.46217880e+01,  1.79065259e-15],
>                     [-3.84140775e+00, -3.84140775e+00],
>                     [-1.92070387e+00, -3.38228415e+00]],
> 
>                     [[-1.92070387e+00, -3.38228415e+00],
>                     [-5.36975882e-16, -2.92316055e+00],
>                     [ 2.72205990e-01, -2.72205990e-01],
>                     [ 6.83230123e-01, -1.36102995e-01]]]
>         primitives.append([all_points, 44.34972*2])
> 
>         all_points = [[[ 1.32009169e+01, -1.32793298e+00],
>                     [ 2.37459679e+01,  0.00000000e+00],
>                     [ 3.25622607e+00,  3.25622607e+00],
>                     [ 1.62811303e+00,  2.81056297e+00]],
> 
>                     [[ 1.62811303e+00,  2.81056297e+00],
>                     [ 1.44808353e-16,  2.36489987e+00],
>                     [-3.47359254e+00,  3.47359254e+00],
>                     [-5.70579875e+00,  1.73679627e+00]],
> 
>                     [[-5.70579875e+00,  1.73679627e+00],
>                     [-7.93800497e+00,  9.72125238e-16],
>                     [-5.49562199e+00, -5.49562199e+00],
>                     [-2.74781099e+00, -3.17571897e+00]],
> 
>                     [[-2.74781099e+00, -3.17571897e+00],
>                     [-1.57210839e-16, -8.55815947e-01],
>                     [ 2.65586596e+00, -2.65586596e+00],
>                     [ 1.32009169e+01, -1.32793298e+00]]]
>         primitives.append([all_points, 43.41156*2])
> 
>         all_points = [[[ 1.52724363e+01, -1.06590506e+01],
>                     [ 9.22677135e+00,  0.00000000e+00],
>                     [ 2.00586698e+01,  2.00586698e+01],
>                     [ 1.00293349e+01,  1.72432240e+01]],
> 
>                     [[ 1.00293349e+01,  1.72432240e+01],
>                     [ 8.83446622e-16,  1.44277782e+01],
>                     [-1.52736686e+01,  1.52736686e+01],
>                     [-1.46296922e+01,  7.63683429e+00]],
> 
>                     [[-1.46296922e+01,  7.63683429e+00],
>                     [-1.39857159e+01,  1.71275622e-15],
>                     [-1.99091489e+01, -1.99091489e+01],
>                     [-9.95457446e+00, -1.62999738e+01]],
> 
>                     [[-9.95457446e+00, -1.62999738e+01],
>                     [-2.33126191e-15, -1.26907988e+01],
>                     [ 2.13181012e+01, -2.13181012e+01],
>                     [ 1.52724363e+01, -1.06590506e+01]]]
>         primitives.append([all_points, 1.9763523*2])
> 
>         all_points = [[[ 1.52724363e+01, -1.06590506e+01],
>                     [ 9.22677135e+00,  0.00000000e+00],
>                     [ 2.00586698e+01,  2.00586698e+01],
>                     [ 1.00293349e+01,  1.72432240e+01]],
> 
>                     [[ 1.00293349e+01,  1.72432240e+01],
>                     [ 8.83446622e-16,  1.44277782e+01],
>                     [-1.52736686e+01,  1.52736686e+01],
>                     [-1.46296922e+01,  7.63683429e+00]],
> 
>                     [[-1.46296922e+01,  7.63683429e+00],
>                     [-1.39857159e+01,  1.71275622e-15],
>                     [-1.99091489e+01, -1.99091489e+01],
>                     [-9.95457446e+00, -1.62999738e+01]],
> 
>                     [[-9.95457446e+00, -1.62999738e+01],
>                     [-2.33126191e-15, -1.26907988e+01],
>                     [ 2.13181012e+01, -2.13181012e+01],
>                     [ 1.52724363e+01, -1.06590506e+01]]]
>         primitives.append([all_points, 1.9763523*2])
> 
> 
>         for primitive in primitives:
>             all_points, extrude_height = primitive
>             sketch = sketches.add(rootComp.xZConstructionPlane)
>             degree = 3
>             knots = [0, 0, 0, 0, 1, 1, 1, 1]
>             weights = [1, 1, 1, 1]
>             # nc = nurbs.controlPointCount
>             splines = sketch.sketchCurves.sketchFixedSplines
>             splines.isFixed=False
> 
> 
> 
>             for control_points in all_points:
>                 point1 = adsk.core.Point3D.create (control_points[0][0],control_points[0][1],0)
>                 point2 = adsk.core.Point3D.create (control_points[1][0],control_points[1][1],0)
>                 point3 = adsk.core.Point3D.create (control_points[2][0],control_points[2][1],0)
>                 point4 = adsk.core.Point3D.create (control_points[3][0],control_points[3][1],0)
>                 points = [point1, point2, point3, point4]
>                 nurbs = adsk.core.NurbsCurve3D.createRational (points, degree, knots, weights, False)
>                 fixed_splines = splines.addByNurbsCurve(nurbs)
>                 fixed_splines.isReference =False
>             distance = adsk.core.ValueInput.createByReal(extrude_height)
>             extrude1 = extrudes.addSimple(sketch.profiles.item(0), distance, adsk.fusion.FeatureOperations.NewBodyFeatureOperation)
>     except:
>         if ui:
>             ui.messageBox('Failed:\n{}'.format(traceback.format_exc()))
> ```

sorry to bother you again,i have some questions about the rotation and translation.
For every extrusion, it needs a plane,how can I get the right plane of every extrusion?
I see that you rotate and translate test points to the coordinate system of the curve to compute sdf, I wonder if the rotation and translation parameters can be used to create the plane of every extrusion. And I dont really understand how quaternion (rotation params) rotate the points (sorry for my poor math ability).
Please talk about these if you have time,Thank you so much!

**Comment by kimren227** [comment]
Yes, transforming the testing points is equivalent to the inverse of transforming the extrusion plane. You can achieve this by either transforming the sketch plane followed by extrusion, or you can extrude first and then transform the extruded shape. 

As for quaternion, it is simply a rotation representation that can be converted into a rotation matrix, axis angle, or Euler angle. Quaternion is used here for two main reasons:  First, it is easier to use as a network output as it does not need to satisfy complicated constraints (e.g. rotation matrix must be an orthogonal matrix with determinate -1). Second, the quaternion is easier to interpolate (you can simply do a linear interpolation between the 4 numbers to get the interpolated rotation). You can find more about rotations and their conversion from [here](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.transform.Rotation.html). For using quaternion and rotation interpolation, you can give this [report](https://web.mit.edu/2.998/www/QuaternionReport1.pdf) a read.
